# Generated by Django 3.2.6 on 2021-08-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('FullName', 'FullName'), ('JOB', 'Job'), ('PhoneNumber', 'PhoneNumber'), ('CompanyName', 'CompanyName'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('ADDRESS', 'Address'), ('DATE', 'Date')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='DataTypeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('value', models.CharField(max_length=225)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.datatype')),
            ],
        ),
        migrations.CreateModel(
            name='DataSchemeColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datatype')),
            ],
        ),
    ]
