# Generated by Django 3.2.6 on 2021-08-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_separator', models.CharField(max_length=25)),
                ('string_character', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='datatypeparameter',
            name='data_type',
        ),
        migrations.RenameField(
            model_name='datatype',
            old_name='type',
            new_name='data_type',
        ),
        migrations.DeleteModel(
            name='DataSchemeColumn',
        ),
        migrations.DeleteModel(
            name='DataTypeParameter',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datatype'),
        ),
    ]
