# Generated by Django 3.2.6 on 2021-08-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_columns_schema_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='column',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.schema'),
            preserve_default=False,
        ),
    ]
