# Generated by Django 3.2.6 on 2021-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210812_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
