# Generated by Django 3.2.6 on 2021-08-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schema_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.datatype')),
            ],
        ),
    ]
