# Generated by Django 3.2.6 on 2021-09-02 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_schemacolumn_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='data_type',
        ),
        migrations.AddField(
            model_name='datatype',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_type', to='core.schemacolumn'),
        ),
    ]
