# Generated by Django 3.2.6 on 2021-09-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210902_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='column',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column', to='core.datatype'),
        ),
    ]
