# Generated by Django 3.2.6 on 2021-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='modification',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready')], default='PROCESSING', max_length=255),
        ),
    ]
